services:
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: vpn_server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - /root/openvpn-data:/etc/openvpn
    sysctls:
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  api:
    container_name: tekra_boy
    build: .
    restart: unless-stopped
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on: [openvpn]
    # по умолчанию API доступен только по VPN (порт наружу не публикуем)
    # если нужно из интернета: раскомментируй следующее и открой UFW 8000/tcp
    # ports:
    #   - "8000:8000"
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

